### ISSUE TITLE
Steps until 2020-05-28

### ISSUE THREAD

**Issue by janCstoffregen** [dasch-swiss/0829-kwa-app#4]
- [ ] einen ersten query zu knora und informationen des Datenmodells @mattssp 
- [ ] ich baue schon eine erste Version der Komponenten für die Sucheingabe und Suchresultate @janCstoffregen (wie im mockup teilweise skizziert)

**Comment by janCstoffregen** [comment]
@flavens we would like to extend the extended search of suid, and make the filters that you apply configurable, would that be ok? would you mind pointing us to the right direction?

**Comment by janCstoffregen** [comment]
I mean where the extended search code is?

**Comment by flavens** [comment]
> @flavens we would like to extend the extended search of suid, and make the filters that you apply configurable, would that be ok? would you mind pointing us to the right direction?

@janCstoffregen this new feature is planned in the dsp-ui library using our new value components. It will have to follow Tobias' design documentation - wip. I would rather prefer you to wait a bit for this implementation and eventually help us to develop it.

**Comment by janCstoffregen** [comment]
@flavens I think we might not be able to wait, can we agree on the configuration file and then exchange my component in the end? Since the NIE-INE project is only going until the end of this year we have to hurry a bit... Of course I would be happy to help you develop this component, is it possible to start this now already? You could delegate part of this component if it's not a problem, or oversee the development and then give feedback if this is what you had in mind? Or should we do another meeting? 
If we just wait there might be a certain insecurity that we don't have enough time left in the end...

**Comment by subotic** [comment]
@janCstoffregen I will talk to @tobiasschweizer today and see when we can have the specification ready. It doesn’t make sense for you to implement something now, which will need to be exchanged in 2 or 3 months.

**Comment by janCstoffregen** [comment]
ok, I agree, thank you!

**Comment by janCstoffregen** [comment]
@flavens same question for the search results, I would like to implement a list of search result, when you are at the end of this list, the next 25 results are loaded, can I implement this or do you want me to use an existing solution from your side?

**Comment by flavens** [comment]
@janCstoffregen we already have search-results components (displaying results as a list or a grid including a pagination index).

**Comment by janCstoffregen** [comment]
@flavens that's great that you already have a search-result component, would you mind pointing me to the right direction? I just don't really know where the right components are. Thanks so much in advance and sorry for the inconvenience!

**Comment by flavens** [comment]
@janCstoffregen the component is part of our "old" module @knora-ui/viewer (Angular 8) and we will be moved to the new library in Angular 9 in the same time as the search components (as mentioned by Ivan in his email). Have you ever tried out our knora-ui modules in an Angular 8 project ou in Inseri?

**Comment by janCstoffregen** [comment]
@flavens I have tried some of the modules, but I am never sure if I have to wait for a stable version or not, and if the updated once are in another Github repo or not, I'm not sure where you find the latest modules. And I am not sure how often this situation occurs, if there is a new Angular version soon, will we be in the same situation?

**Comment by flavens** [comment]
@janCstoffregen so currently we are refactoring the [knora-ui modules](https://github.com/dasch-swiss/knora-ui) in the new repo [knora-ui-ng-lib](https://github.com/dasch-swiss/knora-ui-ng-lib). 
There are 2 main differences between the 2:
- knora-ui-ng-lib (will be renamed "dsp-ui" and this name will stay) is published as [one package on npm](https://www.npmjs.com/package/@dasch-swiss/dsp-ui), it contains 4 modules (action, core, viewer, search) in contrary of the old knora-ui where each "module" was published as its own npm package = 4 npm packages. -> this new way won't change in the future
- we are moving the code and refactoring it to get a stable and flexible structure and to make it work with Angular 9+.
What we are doing now is not meant to change in the future. You will have to upgrade the dependency time to time like any other dependency to get new features and bug fixes.

So (1.) either you start the KWA project with the old knora-ui modules (which are not maintained anymore) with an Angular 8 project and an old version of Knora (v12). But you will have to upgrade everything to Angular 9 with the new library (dasch-swiss/dsp-ui, currently named knora-ui-ng-lib) before December 2020. 
(2.) Or you start with the existing KWA project in Angular 9 and use the release candidate of the library [dasch-swiss/dsp-ui](https://www.npmjs.com/package/@dasch-swiss/dsp-ui) where we will publish new versions very often. Some components are currently missing because we want to refactor the structure during the moving, e.g. the search components (will available during July - see Ivan's email).
I strongly suggest you go for the option 2 (Angular 9). I can provide again the links to our documentation and the release notes. By the way, it would be great if you can give us feedback on the docs in order to improve it. Let me know what's the best for you according to your design document of the app, the specifications and your roadmap.

**Comment by janCstoffregen** [comment]
@flavens thank you for your comprehensive answer, this was very helpful for me! We have decided to go with the second opportunity and follow your recommendation. I will go through the docs, which I wanted to do already for a long time bc of our previous meetings and will give feedback.

Lastly, we'd like to show you our mockups and functionality, to see if we are all talking about the same configurable functionality.

Thank you very much again for your answer and have a nice weekend,
Jan

**Comment by janCstoffregen** [comment]
I'll close this issue for now, #5 contains the steps until next week, thank you for participating in this conversation!
